### ISSUE TITLE
What are the key principles of Redux, and how do they contribute to managing state in a React application?

### ISSUE THREAD

**Issue by theibd56** [theibd56/testRedux#1]

**Comment by Leksizz** [comment]
The only way to change the state is to emit an action, an object describing what happened [1](https://redux.js.org/understanding/thinking-in-redux/three-principles). This ensures:

Neither views nor network callbacks write directly to state
All changes happen in a centralized and strict order
There are no subtle race conditions to watch out for
Actions can be logged, serialized, stored, and replayed for debugging/testing purposes
Making state immutable prevents unexpected bugs and allows for predictable behavior.
